"""
Schemas for Embodied-CoT data.

The Embodied-CoT paper (Zawalski et al.) annotates Bridge v2 trajectories with
structured reasoning traces generated by a large multimodal model (Gemini).
Each trace covers six reasoning dimensions that describe *why* the robot takes
a given action — not just what it does.

HuggingFace dataset: Embodied-CoT/embodied_features_bridge

Assumed column layout (based on public paper + repo inspection):
  steps[i]/observation/image_0          uint8 (H, W, 3)
  steps[i]/action                        float32 (7,)
  steps[i]/language_instruction          str
  steps[i]/reasoning/task_reasoning      str  (may be absent for unannotated steps)
  steps[i]/reasoning/subtask_reasoning   str
  steps[i]/reasoning/move_reasoning      str
  steps[i]/reasoning/gripper_reasoning   str
  steps[i]/reasoning/attribute_reasoning str
  steps[i]/reasoning/spatial_reasoning   str
  episode_metadata/file_path             str  (original Bridge v2 file)

If the actual column names differ, adapt ECoTDatasetReader.COLUMN_MAP in
datasets/embodied_cot.py — the schema objects themselves are column-agnostic.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

import numpy as np

from .base import NumpyArrayMixin, RobotAction


# ---------------------------------------------------------------------------
# Reasoning trace
# ---------------------------------------------------------------------------


@dataclass
class ReasoningTrace:
    """
    Structured reasoning annotation for a single robot action step.

    All six fields correspond to the feature dimensions described in the
    Embodied-CoT paper.  ``raw_response`` stores the original model output
    before any parsing — useful for debugging and re-parsing with updated logic.

    A trace is considered *complete* when the four primary fields are filled.
    Attribute and spatial reasoning are considered supplementary.
    """

    task_reasoning: Optional[str] = None
    """High-level task description: what the robot is trying to accomplish overall."""

    plan: Optional[str] = None
    """Multi-step plan for the trajectory."""

    subtask_reasoning: Optional[str] = None
    """Intermediate subtask label: the specific goal for this phase of the trajectory."""

    subtask_reason: Optional[str] = None
    """Why this subtask was chosen."""

    move_reasoning: Optional[str] = None
    """Arm motion description: which direction/distance to move."""

    move_reason: Optional[str] = None
    """Why this motion was chosen."""

    gripper_reasoning: Optional[str] = None
    """Gripper state rationale: open/close decision and why."""

    attribute_reasoning: Optional[str] = None
    """Object attributes (color, shape, material) relevant to the decision."""

    spatial_reasoning: Optional[str] = None
    """Spatial relationships between objects / end-effector in the scene."""

    raw_response: Optional[str] = None
    """Verbatim model output, stored for auditing and re-parsing."""

    extra: Dict[str, str] = field(default_factory=dict)
    """Extension slot for future reasoning dimensions without breaking the schema."""

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def is_complete(self) -> bool:
        """True if the six primary ECoT reasoning fields are all non-empty."""
        return all(
            [
                self.task_reasoning,
                self.plan,
                self.subtask_reasoning,
                self.subtask_reason,
                self.move_reasoning,
                self.move_reason,
            ]
        )

    def is_empty(self) -> bool:
        """True if no reasoning field has been populated."""
        return not any(
            [
                self.task_reasoning,
                self.plan,
                self.subtask_reasoning,
                self.subtask_reason,
                self.move_reasoning,
                self.move_reason,
                self.gripper_reasoning,
                self.attribute_reasoning,
                self.spatial_reasoning,
            ]
        )

    def filled_fields(self) -> List[str]:
        """Return names of fields that have been populated."""
        candidates = [
            "task_reasoning",
            "plan",
            "subtask_reasoning",
            "subtask_reason",
            "move_reasoning",
            "move_reason",
            "gripper_reasoning",
            "attribute_reasoning",
            "spatial_reasoning",
        ]
        return [f for f in candidates if getattr(self, f)]

    def to_dict(self) -> Dict[str, Any]:
        return {
            "task_reasoning": self.task_reasoning,
            "plan": self.plan,
            "subtask_reasoning": self.subtask_reasoning,
            "subtask_reason": self.subtask_reason,
            "move_reasoning": self.move_reasoning,
            "move_reason": self.move_reason,
            "gripper_reasoning": self.gripper_reasoning,
            "attribute_reasoning": self.attribute_reasoning,
            "spatial_reasoning": self.spatial_reasoning,
            "extra": self.extra,
        }

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> "ReasoningTrace":
        return cls(
            task_reasoning=d.get("task_reasoning"),
            plan=d.get("plan"),
            subtask_reasoning=d.get("subtask_reasoning"),
            subtask_reason=d.get("subtask_reason"),
            move_reasoning=d.get("move_reasoning"),
            move_reason=d.get("move_reason"),
            gripper_reasoning=d.get("gripper_reasoning"),
            attribute_reasoning=d.get("attribute_reasoning"),
            spatial_reasoning=d.get("spatial_reasoning"),
            raw_response=d.get("raw_response"),
            extra=d.get("extra", {}),
        )

    def __repr__(self) -> str:
        filled = self.filled_fields()
        return f"ReasoningTrace(filled={filled})"


# ---------------------------------------------------------------------------
# Observation
# ---------------------------------------------------------------------------


@dataclass
class ECoTObservation(NumpyArrayMixin):
    """
    Single-frame observation from the Embodied-CoT dataset.

    Images can be held in memory (``image``) or referenced by path
    (``image_path``).  Use ``load_image()`` to transparently handle both.
    The loader populates whichever field is appropriate for the use case
    (in-memory for small experiments, path-reference for large-scale runs).
    """

    step_index: int = 0
    image: Optional[np.ndarray] = None       # (H, W, 3) uint8
    image_path: Optional[str] = None         # Absolute path to saved PNG/JPEG

    def load_image(self) -> Optional[np.ndarray]:
        """Return image as numpy array, loading from disk if needed."""
        if self.image is not None:
            return self.image
        if self.image_path is not None:
            from PIL import Image as PILImage
            return np.array(PILImage.open(self.image_path).convert("RGB"))
        return None

    def has_image(self) -> bool:
        return self.image is not None or self.image_path is not None


# ---------------------------------------------------------------------------
# Step
# ---------------------------------------------------------------------------


@dataclass
class ECoTStep(NumpyArrayMixin):
    """One timestep in an Embodied-CoT trajectory."""

    step_index: int = 0
    observation: ECoTObservation = field(default_factory=ECoTObservation)
    action: np.ndarray = field(default_factory=lambda: np.zeros(7, dtype=np.float32))
    """7-DoF end-effector action [Δx, Δy, Δz, Δroll, Δpitch, Δyaw, gripper]."""
    reasoning: Optional[ReasoningTrace] = None
    is_first: bool = False
    is_last: bool = False

    # Per-step ECoT features
    move_primitive: str = ""
    gripper_position: Optional[np.ndarray] = None  # (2,) float32 pixel [x,y]
    bboxes: Any = None  # Variable-length list of bounding boxes
    state_3d: Optional[np.ndarray] = None  # (3,) float32 end-effector [x,y,z]

    def robot_action(self) -> RobotAction:
        """Return action as a named RobotAction object."""
        return RobotAction.from_numpy(self.action)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "step_index": self.step_index,
            "action": self.array_to_list(self.action),
            "reasoning": self.reasoning.to_dict() if self.reasoning else None,
            "is_first": self.is_first,
            "is_last": self.is_last,
            "image_path": self.observation.image_path,
        }


# ---------------------------------------------------------------------------
# Episode
# ---------------------------------------------------------------------------


@dataclass
class ECoTEpisode:
    """
    A complete Embodied-CoT trajectory (episode).

    An episode corresponds to one robot demonstration: a sequence of
    observations, actions, and — optionally — reasoning traces generated
    by a VLM.

    ``metadata`` is a free-form dict for provenance info (split, source file,
    generation run ID, etc.) that does not belong in a typed field.
    """

    episode_id: str = ""
    language_instruction: str = ""
    steps: List[ECoTStep] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)
    source_dataset: str = "embodied_features_bridge"

    # ------------------------------------------------------------------
    # Sequence protocol
    # ------------------------------------------------------------------

    def __len__(self) -> int:
        return len(self.steps)

    def __iter__(self):
        return iter(self.steps)

    def __getitem__(self, idx: int) -> ECoTStep:
        return self.steps[idx]

    # ------------------------------------------------------------------
    # Convenience accessors
    # ------------------------------------------------------------------

    def get_images(self) -> List[Optional[np.ndarray]]:
        """Load all frames. Returns None for steps without images."""
        return [step.observation.load_image() for step in self.steps]

    def get_actions(self) -> np.ndarray:
        """Return (T, 7) action array."""
        return np.stack([step.action for step in self.steps], axis=0)

    def get_reasoning_traces(self) -> List[Optional[ReasoningTrace]]:
        return [step.reasoning for step in self.steps]

    def reasoning_coverage(self) -> float:
        """Fraction of steps that have a reasoning trace."""
        if not self.steps:
            return 0.0
        return sum(1 for s in self.steps if s.reasoning is not None) / len(self.steps)

    def has_any_reasoning(self) -> bool:
        return any(s.reasoning is not None for s in self.steps)

    def annotated_steps(self) -> List[ECoTStep]:
        """Steps that carry a reasoning trace."""
        return [s for s in self.steps if s.reasoning is not None]

    def to_dict(self, include_images: bool = False) -> Dict[str, Any]:
        steps_out = [s.to_dict() for s in self.steps]
        if include_images:
            for raw, d in zip(self.steps, steps_out):
                img = raw.observation.load_image()
                d["image"] = NumpyArrayMixin.array_to_list(img)
        return {
            "episode_id": self.episode_id,
            "language_instruction": self.language_instruction,
            "source_dataset": self.source_dataset,
            "metadata": self.metadata,
            "steps": steps_out,
        }

    def __repr__(self) -> str:
        return (
            f"ECoTEpisode(id={self.episode_id!r}, "
            f"steps={len(self.steps)}, "
            f"reasoning_coverage={self.reasoning_coverage():.0%})"
        )
